### ISSUE TITLE
cant get it to run...

### ISSUE THREAD

**Issue by jjona5** [neduard/acer_5750G_fan_maximiser#4]
I downloaded the script directly and tried to run on my linux mint powered 5750g

perl acer_5750G_fan_controller.pl MAX
Bareword found where operator expected at acer_5750G_fan_controller.pl line 6, near ""en" class"
	(Missing operator before class?)
Bareword found where operator expected at acer_5750G_fan_controller.pl line 25, near "<title>acer_5750G_fan_maximiser"
	(Missing operator before acer_5750G_fan_maximiser?)
Can't modify numeric lt (<) in scalar assignment at acer_5750G_fan_controller.pl line 6, near ""en" class"
syntax error at acer_5750G_fan_controller.pl line 6, near ""en" class"
Unrecognized character \xC2; marked by <-- HERE after at master <-- HERE near column 76 at acer_5750G_fan_controller.pl line 25.

**Comment by LeonardKoenig** [comment]
Guessing from the error-codes you have downloaded the website rendering the file instead of the file itself.

**Comment by neduard** [comment]
@jjona5 try again using the raw file: https://raw.githubusercontent.com/neduard/acer_5750G_fan_maximiser/master/acer_5750G_fan_controller.pl

**Comment by jjona5** [comment]
Thank you so much. I had right clicked and downloaded but that was the issue.

**Comment by neduard** [comment]
@jjona5 no problem, glad it works :)
